import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
z = np.random.normal(size=1000)
x = np.random.binomial(n=10,p=0.2,size=10)
print("normal distribution ",z)
print("binomial distribution ", x)
#sns.distplot(random.binomial(n=100, p=0.5, size=1000), hist=False, label= 'binomial')
#sns.distplot(random.normal(loc=50, scale=5, size=1000), hist=False, label='normal')
#print(np.random.poisson(lam=2, size=1000))
#sns.distplot(np.random.poisson(lam=2, size=1000), kde=False, label="poisson")
#plt.show()
arr = np.arange(1,11)
arr2 = np.arange(11,21)
print(arr)
print(np.log2(arr))
print(np.log10(arr))
print(np.log(arr))
print(arr)
print(arr2)
print(np.add(arr,arr2))
print(np.sum([arr,arr2], axis=1))
print(np.cumsum(arr),np.cumsum(arr2))
print(np.prod([arr,arr2]))
print(np.prod(arr))
print(np.prod([arr,arr2], axis=1))
print(np.cumprod(arr))
arr1 = np.arange(2,50,5)
print(arr1)
print(np.diff(arr1))
print(np.diff(arr1, n=4))
print(np.lcm(6,7))
print(np.lcm.reduce(arr))
print(np.gcd(6,9))
print(np.gcd.reduce(arr1))

